# Generated by Django 4.1.7 on 2023-11-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_author', to='blog.user'),
        ),
        migrations.DeleteModel(
            name='QuestionLikes',
        ),
    ]
