# Generated by Django 4.1.7 on 2023-11-10 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.CreateModel(
            name='QuestionLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.question')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.profile')),
            ],
        ),
    ]
