# Generated by Django 4.1.7 on 2023-11-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_answer_likes_remove_question_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerLikes',
            new_name='AnswerLike',
        ),
        migrations.RenameModel(
            old_name='QuestionLikes',
            new_name='QuestionLike',
        ),
    ]
