# Generated by Django 4.1.7 on 2023-11-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0013_remove_profile_email_remove_profile_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
