# Generated by Django 4.1.7 on 2023-11-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_reaction_alter_profile_rating_delete_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], default='L', max_length=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_reactions', to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], default='L', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_reactions', to='blog.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.question')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
